export const baseUrl = 'http://localhost:8080';
export const patientUrl = baseUrl + '/mes-patients';
export const accueilUrl = baseUrl + '/accueil';
export const creationPatientUrl = baseUrl + '/creer-patient';
export const quizsErgoUrl = baseUrl + '/mes-quizs';
export const themeListUrl = baseUrl + '/theme-list';
export const creationQuizUrl = baseUrl +'/creer-quiz';
export const pageStatGeneraleUrl = baseUrl + '/page-stat-acceuil';
export const pageAideUrl = baseUrl + '/page-aide';
