services:
  backend:
    build: ../backend/
    ports:
      - "8000:9428"
    image: backend:backend-node #nom_de_l'image_back
  frontend:
    build: ../front-end/
    ports:
      - "8080:4200"
    image: front:frontend #nom_de_l'image_front